- hosts: all
  tasks:
    - name: chell
      shell: git remote -v
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: chell
      shell: git log origin/master..HEAD
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: shell
      shell:
        cmd: |
          set -e
          set -x
          result=0
          for commit in $(git cherry -v origin/{{ zuul.branch }} HEAD | cut -d " " -f2)
          do
            if ! git show -s $commit | grep -q "Signed-off-by:"; then
              echo "Commt $commit does not have a Signed-off-by header"
              git show $commit
              result=1
            fi
          done
        chdir: "{{ zuul.project.src_dir }}"
        executable: /bin/bash
