- hosts: all
  tasks:
    - name: shell
      shell:
        cmd: |
          set -e
          result=0
          for commit in $(git cherry -v origin/{{ zuul.branch }} HEAD | cut -d " " -f2)
          do
            if ! git show -s $commit | grep -q "Signed-off-by:"; then
              echo "Commt $commit does not have a Signed-off-by header"
              git show -s $commit
              result=1
            fi
          done
          exit $result
        chdir: "{{ zuul.project.src_dir }}"
        executable: /bin/bash
