- hosts: all
  tasks:
    - name: chell
      shell: git remote -v
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: chell
      shell: git log origin/master..HEAD
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: shell
      shell:
        cmd: |
          git cherry -v origin/{{ zuul.branch }} HEAD | cut -d\' \' -f2
        chdir: "{{ zuul.project.src_dir }}"
        executable: /bin/bash
