- hosts: all
  tasks:
    - name: shell
      shell: |
        for commit in $(git cherry master | cut -d " " -f2)
        do
            echo $commit
        done
      args:
        chdir: "{{ zuul.project.src_dir }}"
