- job:
    name: awx-tox-base
    parent: tox
    pre-run: playbooks/awx-tox-base/pre.yaml
    required-projects:
      - name: github.com/ansible/awx
    vars:
      zuul_work_dir: ~/src/github.com/ansible/awx
    nodeset: fedora-latest-1vcpu

- job:
    name: awx-tox-linters-api
    parent: awx-tox-base
    vars:
      tox_envlist: api-lint

- job:
    name: awx-tox-linters-ui
    parent: tox-nodejs-npm
    pre-run: playbooks/awx-tox-base/pre.yaml
    required-projects:
      - name: github.com/ansible/awx
    vars:
      tox_envlist: ui-lint
      zuul_work_dir: ~/src/github.com/ansible/awx
    nodeset: fedora-latest-1vcpu

- project:
    check:
      jobs:
        - awx-tox-linters-api
        - awx-tox-linters-ui
