- job:
    name: sandbox-metal3-dev-env
    parent: unittests
    pre-run: tests/playbooks/pre.yaml
    run: tests/playbooks/run.yaml
    required-projects:
      - github.com/metal3-io/metal3-dev-env
    nodeset: centos-7-8vcpu
    timeout: 7200

- nodeset:
    name: centos-7-8vcpu
    nodes:
      - name: centos-7
        label: centos-7-8vcpu

- project:
    check:
      jobs:
        - sandbox-metal3-dev-env
