- nodeset:
    name: nxos-python27
    nodes:
      - name: ubuntu-bionic
        label: ubuntu-bionic-rdocloud
    groups:
      - name: controller
        nodes:
          - ubuntu-bionic

- job:
    name: testing-nxos
    run: playbooks/run.yaml
    nodeset: nxos-python27

- project:
    check:
      jobs:
        - testing-nxos
