- job:
    name: build-ansible-collections
    description: |
      Build ansible collection
    pre-run: playbooks/ansible-collection/pre.yaml
    run:
      - playbooks/ansible-collection/run-pre.yaml
      - playbooks/ansible-collection/run.yaml
    post-run:
      - playbooks/ansible-collection/post.yaml
    required-projects:
      - github.com/ansible-network/releases
    nodeset: centos-8-1vcpu

- project:
    check:
      jobs:
        - build-ansible-collections
    post:
      jobs:
        - release-ansible-collection-galaxy-dev
    pre-rlease:
      jobs:
        - release-ansible-collection-galaxy-dev
    release:
      jobs:
        - release-ansible-collection-galaxy-dev
