- job:
    name: sandbox-nxos-test
    run: playbooks/sandbox-nxos-test/run.yaml
    nodeset:
      nodes:
        - name: fedora-latest
          label: fedora-29-1vcpu
        - name: applicance
          label: ansible-network-nxos

- project:
    templates:
      - build-tox-docs
    post:
      jobs:
        - sandbox-nxos-test
        - tox-docs
