- job:
    name: builder-test
    run: playbooks/run.yaml
    nodeset: centos-8-1vcpu

- project:
    check:
      jobs:
        - builder-test
    pre-rlease:
      jobs:
        - release-ansible-python
    release:
      jobs:
        - release-ansible-python
