- job:
    name: sandbox-metal3-dev-env
    parent: unittests
    run: tests/playbooks/run.yaml
    required-projects:
      - github.com/metal3-io/metal3-dev-env
    nodeset: centos-7-1vcpu

- project:
    check:
      jobs:
        - sandbox-metal3-dev-env
