- job:
    name: test-sandbox
    run: playbooks/run.yaml

- project:
    check:
      jobs:
        - build-ansible-collection
        - test-sandbox:
            dependencies:
              - build-ansible-collection
    post:
      jobs:
        - release-ansible-collection-galaxy-dev
    pre-rlease:
      jobs:
        - release-ansible-collection-galaxy-dev
    release:
      jobs:
        - release-ansible-collection-galaxy-dev
