- job:
    name: molecule-demo-base
    parent: tox
    required-projects:
      - name: github.com/ansible/molecule
    nodeset: fedora-latest-1vcpu
    vars:
      zuul_work_dir: /home/zuul/src/github.com/ansible/molecule

- job:
    name: molecule-demo-lint
    parent: molecule-demo-base
    vars:
      tox_envlist: lint

- job:
    name: molecule-demo-py37-ansible25-unit
    parent: molecule-demo-base
    vars:
      tox_envlist: py37-ansible25-unit

- project:
    check:
      jobs:
        - molecule-demo-lint
        - molecule-demo-py37-ansible25-unit
    post:
      jobs:
        - tox-docs
