- job:
    name: sandbox-metal3-dev-env
    parent: unittests
    pre-run: tests/playbooks/pre.yaml
    run: tests/playbooks/run.yaml
    required-projects:
      - github.com/metal3-io/metal3-dev-env
    nodeset: centos-7-4vcpu

- project:
    check:
      jobs:
        - sandbox-metal3-dev-env
