- nodeset:
    name: ubuntu-bionic-1vcpu
    nodes:
      - name: ubuntu-bionic
        label: ubuntu-bionic-1vcpu

- job:
    name: galaxy-quick-start
    run: playbooks/run.yaml
    required-projects:
      - name: github.com/ansible/galaxy
    nodeset: ubuntu-bionic-1vcpu

- project:
    check:
      jobs:
        - galaxy-quick-start
