- job:
    name: tox-molecule-demo
    parent: tox
    required-projects:
      - github.com/ansible/molecule
    vars:
      tox_envlist: lint
      zuul_work_dir: /home/zuul/src/github.com/ansible/molecule

- project:
    templates:
      - build-tox-docs
    post:
      jobs:
        - tox-docs

- pipeline:
    check:
      jobs:
        - tox-molecule-demo
