---
- hosts: all
  tasks:
    - name: Setup tox role
      include_role:
        name: tox
      vars:
        tox_envlist: venv
        tox_extra_args: -vv --notest
        tox_install_siblings: false

    - name: Run build-ansible-collection role
      include_role:
        name: build-ansible-collection
      vars:
        ansible_galaxy_executable: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/.tox/venv/bin/ansible-galaxy"
        zuul_work_dir: "{{ ansible_user_dir }}/{{ item.src_dir }}"
      with_items: "{{ zuul.projects.values() | list }}"
