- hosts: all
  tasks:
    - name: Executor install-docker role
      include_role:
        name: install-docker
      vars:
        use_upstream_docker: false

    - name: Ensure docker-compose is installed
      become: true
      package:
        name: docker-compose
        state: installed

    - name: Build docker containers
      shell: make dev/build
      args:
        chdir: "{{ zuul.projects['github.com/ansible/galaxy'].src_dir }}"

    - name: Run docker-compose up
      shell: make dev/up_detached
      args:
        chdir: "{{ zuul.projects['github.com/ansible/galaxy'].src_dir }}"

    - name: Print list of images
      command: docker image ls --all --digests --no-trunc

    - name: Wait for galaxy to start
      uri:
        url: http://localhost:8000
        method: GET
      register: result
      until: result.status == 200 and result.redirected == false
      retried: 120

    - name: Create admin user
      shell: make dev/createsuperuser
      args:
        chdir: "{{ zuul.projects['github.com/ansible/galaxy'].src_dir }}"
