- hosts: all
  tasks:
    - name: Executor install-docker role
      include_role:
        name: install-docker

    - name: Ensure docker-compose is installed
      become: true
      package:
        name: docker-compose
        state: installed

    - name: Run docker-compose up
      shell: docker-compose up -d -g galaxy -f compose.yml
      args:
        chdir: "{{ zuul.projects['github.com/ansible/galaxy'].src_dir }}/scripts/docker/dev"
